version: "3.9"

services:
    # frontend:
    #     container_name: shoppingify-frontend
    #     build:
    #         context: ./frontend
    #     ports:
    #         - "3000:3000"
    #     volumes:
    #         - ./frontend:/app
    #         - react_node_modules:/app/node_modules
    #     environment:
    #         - CHOKIDAR_USEPOLLING=true
    #     tty: true
    #     stdin_open: true
    backend: 
        container_name: shoppingify-backend
        build: 
            context: ./backend
        volumes:
          - ./backend:/app
          - node_modules:/app/node_modules
        ports: 
            - "5000:5000"
        environment:
            - CHOKIDAR_USEPOLLING=true
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_DB=shoppingify
    db:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_PORT=5432
          - POSTGRES_DB=shoppingify
        volumes: 
          - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    admin:
        image: adminer
        restart: always
        depends_on: 
          - db
        ports:
          - 8080:8080
volumes:
    react_node_modules:
    node_modules: